create table if not exists public.plants (
    id uuid primary key default gen_random_uuid(),
    name text not null unique
);
create table if not exists public.machines (
    id uuid primary key default gen_random_uuid(),
    plant_id uuid not null references public.plants(id) on delete cascade,
    name text not null,
    line text,
    primary_metric text not null,
    created_at timestamptz not null default now(),
    constraint machines_primary_metric_check
        check (primary_metric in ('rpm', 'temperature', 'vibration', 'amps')),
    constraint machines_plant_name_unique unique (plant_id, name)
);
create table if not exists public.machine_api_keys (
    id uuid primary key default gen_random_uuid(),
    machine_id uuid not null references public.machines(id) on delete cascade,
    key_hash text not null,
    is_active boolean not null default true,
    created_at timestamptz not null default now(),
    constraint machine_api_keys_machine_hash_unique unique (machine_id, key_hash)
);
create table if not exists public.readings (
    id bigint generated by default as identity primary key,
    machine_id uuid not null references public.machines(id) on delete cascade,
    ts_device timestamptz null,
    ts_server timestamptz not null default now(),
    metric text not null,
    value double precision not null,
    constraint readings_metric_check
        check (metric in ('rpm', 'temperature', 'vibration', 'amps'))
);
create index if not exists readings_machine_metric_tsserver_desc_idx
    on public.readings (machine_id, metric, ts_server desc);
